# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedy_knapsack_rcpp <- function(x, WD) {
    .Call('_knapsack_greedy_knapsack_rcpp', PACKAGE = 'knapsack', x, WD)
}

knapsack_dynamic_rcpp <- function(x, WD) {
    .Call('_knapsack_knapsack_dynamic_rcpp', PACKAGE = 'knapsack', x, WD)
}

brute_force_knapsack_rcpp <- function(x, WD) {
    .Call('_knapsack_brute_force_knapsack_rcpp', PACKAGE = 'knapsack', x, WD)
}

