# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' using brute force algorithm (C++) to solve knapsack problem 
NULL

brute_force_knapsack_rcpp <- function(x, WD) {
    .Call('_knapsack_brute_force_knapsack_rcpp', PACKAGE = 'knapsack', x, WD)
}

